### ISSUE TITLE
Refactor Gorse Client for Better Maintainability

### ISSUE THREAD

**Issue by nebHailemariam** [gorse-io/Gorse.NET#16]
Hi @zhenghaoz ,

The `Gorse.cs` file currently contains all API methods and data model definitions, making it difficult to maintain. I propose the following changes:

1. **Separate Data Models**: Move `User`, `Item`, `Feedback`, etc., definitions into a dedicated `Models` folder to reduce `Gorse.cs` from being cluttered.

2. **Use Partial Classes for API Methods**: Break the `Gorse` client into partial classes (e.g., `UserAPI`, `ItemAPI`, `FeedbackAPI`) in separate files, grouping methods logically for easier navigation. This will not change how the API will be accessed by the end-users. This will **not** be a **breaking change**. Users will still be able to for instance be able to call `client.InsertFeedback` method as they have done before. This will only be a physical separation of the Gorse APIs but they will all be in the same `Gorse` class. For more information about partial classes, look here: https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods 

3. **Organize Tests by Category**: Create separate test files (e.g., `UserTests.cs`, `ItemTests.cs`) to improve modularity.

### Benefits
These changes will make the codebase more modular and readable supporting simpler maintenance.

What are your thoughts @zhenghaoz? Let me know if I should proceed with these changes!

**Comment by zhenghaoz** [comment]
Seems good. I have added you as its maintainer. I think you know more about .NET than me.

**Comment by nebHailemariam** [comment]
I'm humbled, thank you! I will start working on it!

**Comment by nebHailemariam** [comment]
![image](https://github.com/user-attachments/assets/0b920bd3-5260-43d9-a8a9-3cb5a233c109)
![image](https://github.com/user-attachments/assets/d006230f-8690-4ffb-a4e9-6f4fde1a7780)

I've made PR and closed this issue:

1. Moves data models to a Models folder.
2. Splits API methods into partial classes for better organization.
3. Organizes tests into separate files.
4. Add all classes and implement almost all API calls defined in the Gorse documentation.
5. Ensures 100% test coverage for all methods.

These changes improve code clarity and maintainability without breaking existing functionality.
